### ISSUE TITLE
Crashes when accessing localhost:8889 via GET

### ISSUE THREAD

**Issue by murphyj** [mrak/stubby4node#30]
I have a vanilla install of stubby version 0.2.10 with:

```
npm install -g stubby && stubby
```
I point my browser at `localhost:8889` to find out if my endpoints are registered. Stubby server crashes with the following error message on terminal.

```
/usr/local/lib/node_modules/stubby/lib/portals/admin.js:79
        if (data.length === 0) { _this.noContent(response); }
                                 ^
ReferenceError: _this is not defined
    at callback (/usr/local/lib/node_modules/stubby/lib/portals/admin.js:79:34)
    at Endpoints.gather (/usr/local/lib/node_modules/stubby/lib/models/endpoints.js:79:3)
    at Admin.goGET (/usr/local/lib/node_modules/stubby/lib/portals/admin.js:83:27)
    at Admin.server (/usr/local/lib/node_modules/stubby/lib/portals/admin.js:205:21)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2108:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1966:22)
    at TCP.onread (net.js:527:27)
```
I presume this is because the line should read...

```
if (data.length === 0) { self.noContent(response); }
```
As there is no assigned variable _this

**Comment by mrak** [comment]
The recent rewrite from CoffeeScript to JavaScript may have illustrated some untested code. Thanks for reporting and providing a fix!
