### ISSUE TITLE
TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by ryuichi7** [mrak/stubby4node#56]
Hi, I'm using stubby for the first time and when I install using npm (sudo npm install -g stubby) and try to run the stubby server I get this error:

`brett$ stubby -d config.yml
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Object.getArgs (/Users/brett/.node/lib/node_modules/stubby/src/console/cli.js:141:38)
    at setupStartOptions (/Users/brett/.node/lib/node_modules/stubby/src/main.js:60:18)
    at Stubby.start (/Users/brett/.node/lib/node_modules/stubby/src/main.js:92:12)
    at Object.<anonymous> (/Users/brett/.node/lib/node_modules/stubby/bin/stubby:7:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)`

the CLI won't respond to any commands, it just throws the path error.
i'm using node -v 6.0.0

I also tried adding ./bin/stubby to my $PATH to no avail.

This may very well be just an issue on my system, but I thought I'd raise an issue to see if anyone else had this problem. Any help is greatly appreciated

**Comment by ryuichi7** [comment]
Figured out that it's because I was running node v6.0.0. thanks

**Comment by jxc876** [comment]
Same issue here, downgrading to v5 or v4 fixes the issue.

**Comment by mrak** [comment]
Could you post the output of `stubby --version`?

**Comment by jxc876** [comment]
`stubby --version: 0.2.13`
